---
name: Test-Virtual-Filesystem
version: 0.01
author:
  - 'Chris Dolan <cdolan@cpan.org>'
abstract: Validate a filesystem
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Readonly: 0
  Test::Class: 0.24
  Test::More: 0.62
  perl: 5.6.0
recommends:
  Test::Memory::Cycle: 1.02
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Test::Virtual::Filesystem:
    file: lib/Test/Virtual/Filesystem.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
