---
name: Test-Virtual-Filesystem
version: 0.11
author:
  - 'Chris Dolan <cdolan@cpan.org>'
abstract: Validate a filesystem
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Attribute::Handlers: 0.78
  Carp: 0
  File::Spec: 0
  List::MoreUtils: 0
  POSIX: 0
  Readonly: 1
  Test::Class: 0.24
  Test::More: 0.62
  base: 0
  perl: 5.8.0
build_requires:
  Test::Builder::Tester: 1.04
recommends:
  File::ExtAttr: 1
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Test::Virtual::Filesystem:
    file: lib/Test/Virtual/Filesystem.pm
    version: 0.11
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
